language: node_js

node_js:
- '0.10'

before_install:
- npm install -g jshint
- gem install sass compass

script:
- jshint .
- compass compile

notifications:
  email:
    recipients:
      - jeffreyzhang@vip.qq.com