language: node_js

node_js:
- '0.10'

before_install:
- npm install -g jshint
- gem install sass compass modular-scale sassy-math

script:
- jshint .
- compass compile

notifications:
  email:
    recipients:
    - secure: i8QL+MzSV/ei/I+cCA0FRWo64THumQun94vvYVqahe5x27tKyVoAjvR0IBn97pXVAN7hbsRBtooe10AmPB+PbQmwgky2knt8I9kTOfCtRuV/rsm7FcH3nUTxpeipZsfr7z3+/xv1f7kiGjGwZDtr6Bvjsju2v5PNAn912FWBZZw=