language: node_js

node_js:
- '0.10'

before_install:
- npm install -g jshint
- gem install sass compass

script:
- jshint .
- compass compile

notifications:
  email:
    recipients:
    - secure: QBMbGh61xZJIP+sFbQiS1I+ASMj5DhkIuOSo5yY4lymbhZJascPAQ1kX2LS8LmW4mZIWREndAVJ/sNwRomkeBUsmwh0WA3VWmyBLNYDA/gVFIDdBImXgNffLpH6xeAEd3+8CA9HgP44NWM7gponyaXvCSohhOASngrfx6ugluSY=